name: destroy-infra
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      deployment_name:
        description: "Specify deployment name. Must have an output named 'resource_groups' which is an array with the names of the resource groups' to be deleted."
        default: dwg-prod-deployment
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
        
jobs:
  approve:
    name: approve-infra-teardown
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1.9.0
        with:
          approvers: christosgalano
          minimum-approvals: 1
          issue-title: "Approve teardown of infrastructure regarding deployment ${{ inputs.deployment_name }}"
          secret: ${{ secrets.GITHUB_TOKEN }}
  destroy:
    name: destroy-infra
    needs: approve
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete resource groups
        shell: pwsh
        run: |
          $resource_groups = az deployment sub show -n ${{ inputs.deployment_name }} --query properties.outputs.resource_groups.value | convertfrom-json
          $resource_groups | foreach -parallel { Write-Host "Deleting resource group $_ ..."; az group delete -n $_ -y }